name: First workflow

on:
  push:
    branches:
      - main
    
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print a welcome message
        run: echo "Hello to the git actions world"

      - name: Download the source code
        uses: actions/checkout@v5.0.0

      
      - name: Create a python file
        run: echo "print('hello, World!')" > main.py
        
      - name: List all dirs and files
        run: ls -al


  
