on:
  workflow_dispatch:


jobs:
  job1:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: [windows-latest , ubuntu-latest , macos-latest]
        node_versions: [14.x,15.x,16.x]
  
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/setup-node@v6.0.0
        with:
          node-version: ${{matrix.node_versions}}
