on:
  push:
    branches:
      - main
      - "release/**"
    paths:
      - "src/**"

  pull_request:
    branches:
      - main
      - "release/**"

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: repo-chechout
        uses: actions/checkout@v5.0.0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify your Python version
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: run tests
        run: pytest


