on:
  push:
    branches:
      - main
      - "release/**"
    paths:
      - "src/**"

  pull_request:
    branches:
      - main
      - "release/**"

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: repo-chechout
        uses: actions/checkout@v5.0.0

      - name: install dependancies
        run: pip install reqrequirements.txt

      - name: run tests
        run: pytest
