on:
  workflow_dispatch:



jobs:
  job1:
  
    runs-on: ubuntu-latest
    steps:
      - run: |
          deprecated=true
          if [[ deprecated ]]; then
          echo "::warning:: Please note your code have some deprecated modules"
          fi
          
